version: '3'
services:
  app:
    container_name: bahamas_app
    build:
      context: bahamas
      dockerfile: Dockerfile
    ports:
        - 8080:8080
  database:
    container_name: bahamas_postgres
    env_file: .env.postgres
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    external: false
